version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          command: |
            mkdir -p ~/.gradle
            echo "artifactory_user=$ARTIFACTORY_USER" >> ~/.gradle/gradle.properties
            echo "artifactory_password=$ARTIFACTORY_PASS" >> ~/.gradle/gradle.properties
            echo "artifactory_contextUrl=$ARTIFACTORY_CONTEXT_URL" >> ~/.gradle/gradle.properties
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew generatePomFileForMavenJavaPublication artifactoryPublish